{
 "title": "clab",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Devices", "query": { "query": "label_values(source)" } }
  ]
 },
 "panels": [
  {
   "title": "BGP Total Active routes",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_srl_bgp_stats_srl_nokia_network_instance_network_instance_protocols_srl_nokia_bgp_bgp_statistics_total_active_routes{network_instance_name=\"default\", source=\"$Devices\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BGP Peers Established",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_srl_bgp_stats_srl_nokia_network_instance_network_instance_protocols_srl_nokia_bgp_bgp_statistics_up_peers{network_instance_name=\"default\", source=\"$Devices\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BGP Total Configured Peers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_srl_bgp_stats_srl_nokia_network_instance_network_instance_protocols_srl_nokia_bgp_bgp_statistics_total_peers{network_instance_name=\"default\", source=\"$Devices\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IN - OUT Octets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "gnmic_srl_if_stats_srl_nokia_interfaces_interface_statistics_in_octets{interface_name=\"ethernet-1/1\", source=\"$Devices\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_srl_if_stats_srl_nokia_interfaces_interface_statistics_out_octets{interface_name=\"ethernet-1/1\", source=\"$Devices\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_srl_if_stats_srl_nokia_interfaces_interface_statistics_in_octets{interface_name=\"ethernet-1/11\", source=\"$Devices\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_srl_if_stats_srl_nokia_interfaces_interface_statistics_out_octets{interface_name=\"ethernet-1/11\", source=\"$Devices\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IN OUT BPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "gnmic_srl_if_traffic_rate_srl_nokia_interfaces_interface_traffic_rate_in_bps{interface_name=\"ethernet-1/1\", source=\"$Devices\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_srl_nokia_interfaces_interface_traffic_rate_out_bps{interface_name=\"ethernet-1/1\", source=\"$Devices\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_srl_nokia_interfaces_interface_traffic_rate_in_bps{interface_name=\"ethernet-1/11\", source=\"$Devices\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gnmic_srl_if_traffic_rate_srl_nokia_interfaces_interface_traffic_rate_out_bps{interface_name=\"ethernet-1/11\", source=\"$Devices\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_srl_mem_srl_nokia_platform_platform_srl_nokia_platform_control_control_srl_nokia_platform_memory_memory_utilization{source=\"$Devices\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_srl_cpu_srl_nokia_platform_platform_srl_nokia_platform_control_control_srl_nokia_platform_cpu_cpu_total_instant{control_slot=\"A\", source=\"$Devices\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}